### ISSUE TITLE
TypeError: cannot pickle 'Environment' object (Win10)

### ISSUE THREAD

**Issue by jessephamel** [acids-ircam/RAVE#71] opened 2022-05-20 20:01 UTC
Windows 10, Python 3.9 + conda, all dependencies seem to be installed.

CUDA installed and nvidia-smi works but the script seems to not see my device.

PS C:\Users\jesse\rave> python train_rave.py -c small --name kicks --wav C:\Users\jesse\RAVE\kicks\out_44100 --preprocessed C:\Users\jesse\RAVE\kicks_temp\kicks\rave --sr 44100
Recursive search in C:\Users\jesse\RAVE\kicks\out_44100
audio_00524_00000.wav: 100%|████████████████████████████████████████████████████████| 525/525 [00:03<00:00, 135.07it/s]
C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py:487: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 4 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
No GPU found.
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs

  | Name          | Type                | Params
------------------------------------------------------
0 | pqmf          | CachedPQMF          | 16.7 K
1 | loudness      | Loudness            | 0
2 | encoder       | Encoder             | 1.4 M
3 | decoder       | Generator           | 3.4 M
4 | discriminator | StackDiscriminators | 16.9 M
------------------------------------------------------
21.7 M    Trainable params
0         Non-trainable params
21.7 M    Total params
86.972    Total estimated model params size (MB)
Sanity Checking: 0it [00:00, ?it/s]Traceback (most recent call last):
  File "C:\Users\jesse\rave\train_rave.py", line 171, in <module>
    trainer.fit(model, train, val, ckpt_path=run)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1234, in _run
    results = self._run_stage()
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1343, in _run_train
    self._run_sanity_check()
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 1411, in _run_sanity_check
    val_loop.run()
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\loops\base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\loops\dataloader\evaluation_loop.py", line 153, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\loops\base.py", line 199, in run
    self.on_run_start(*args, **kwargs)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\loops\epoch\evaluation_epoch_loop.py", line 87, in on_run_start
    self._data_fetcher = iter(data_fetcher)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\pytorch_lightning\utilities\fetching.py", line 178, in __iter__
    self.dataloader_iter = iter(self.dataloader)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 368, in __iter__
    return self._get_iterator()
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 314, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\utils\data\dataloader.py", line 927, in __init__
    w.start()
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'Environment' object
PS C:\Users\jesse\rave> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\jesse\AppData\Local\Programs\Python\Python39\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by jessephamel** [comment] 2022-05-22 23:57
I got it working on CPU by setting num_workers=0, but still can't get it to see my GPU.

**Comment by jessephamel** [comment] 2022-05-23 01:46
GPU is working now. Had to install torch==1.11.0+cu113. I still need to run with num_workers 0. I'm not sure if this is considered an issue.

**Comment by caillonantoine** [comment] 2022-05-24 12:56
duplicate of #10

**Closed by caillonantoine** 2022-05-24 12:56 UTC
