### ISSUE TITLE
help with this

### ISSUE THREAD

**Issue by cyrstem** [acids-ircam/RAVE#67] opened 2022-05-14 03:40 UTC
help with this error what im i doing wrong ?
```
Sanity Checking DataLoader 0: 100%|███████████████████████████████████████████████| 1/1 [00:00<00:00,  2.62it/s]Traceback (most recent call last):
  File "/home/jacos/ML/RAVE/train_rave.py", line 166, in <module>
    trainer.fit(model, train, val, ckpt_path=run)
  File "/home/jacos/anaconda3/envs/RAVE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "/home/jacos/anaconda3/envs/RAVE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/jacos/anaconda3/envs/RAVE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/jacos/anaconda3/envs/RAVE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/home/jacos/anaconda3/envs/RAVE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/home/jacos/anaconda3/envs/RAVE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_train
    self._run_sanity_check()
  File "/home/jacos/anaconda3/envs/RAVE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1411, in _run_sanity_check
    val_loop.run()
  File "/home/jacos/anaconda3/envs/RAVE/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 211, in run
    output = self.on_run_end()
  File "/home/jacos/anaconda3/envs/RAVE/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 187, in on_run_end
    self._evaluation_epoch_end(self._outputs)
  File "/home/jacos/anaconda3/envs/RAVE/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 309, in _evaluation_epoch_end
    self.trainer._call_lightning_module_hook("validation_epoch_end", output_or_outputs)
  File "/home/jacos/anaconda3/envs/RAVE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1593, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/jacos/ML/RAVE/rave/model.py", line 721, in validation_epoch_end
    pca = PCA(z.shape[-1]).fit(z.cpu().numpy())
  File "/home/jacos/anaconda3/envs/RAVE/lib/python3.9/site-packages/sklearn/decomposition/_pca.py", line 382, in fit
    self._fit(X)
  File "/home/jacos/anaconda3/envs/RAVE/lib/python3.9/site-packages/sklearn/decomposition/_pca.py", line 457, in _fit
    return self._fit_full(X, n_components)
  File "/home/jacos/anaconda3/envs/RAVE/lib/python3.9/site-packages/sklearn/decomposition/_pca.py", line 475, in _fit_full
    raise ValueError(
ValueError: n_components=128 must be between 0 and min(n_samples, n_features)=64 with svd_solver='full'

```

**Comment by caillonantoine** [comment] 2022-05-14 08:15
duplicate of #45

**Closed by caillonantoine** 2022-05-14 08:15 UTC
