### ISSUE TITLE
NotImplementedError: Support for `validation_epoch_end` has been removed in v2.0.0.

### ISSUE THREAD

**Issue by nightshining** [acids-ircam/RAVE#219] opened 2023-03-15 19:03 UTC
Error upon training, using the code from v2 colab notebook:

NotImplementedError: Support for `validation_epoch_end` has been removed in v2.0.0. `RAVE` implements this method. You can use the `on_validation_epoch_end` hook instead. To access outputs, save them in-memory as instance attributes. You can find migration examples in https://github.com/Lightning-AI/lightning/pull/16520.

**Comment by tmroyal** [comment] 2023-03-15 19:20
Confirmed with my own notebook in Paperspace, which has been working for a week. 

It looks like Lightning AI just launched a new version today. Maybe adding `,<2.0.0` to requirements.txt after pytorch_lightning can be a valid stopgap before adjusting the code to support Lightning 2.0?

**Comment by tmroyal** [comment] 2023-03-15 19:34
rassibassi on the discourse channel suggested this as a temporary solution

`!/content/miniconda/bin/pip install --quiet pytorch_lightning==1.9.4`

**Comment by caillonantoine** [comment] 2023-03-16 08:34
Good catch ! I have pinned lightning to 1.9.0 in ce474c9 , it should be fixed now ! I'll update the code later :)

**Closed by caillonantoine** 2023-03-16 08:34 UTC

**Comment by tmroyal** [comment] 2023-03-16 22:02
Thanks!!!!!
