### ISSUE TITLE
prior model training issue

### ISSUE THREAD

**Issue by meadow163** [acids-ircam/RAVE#79] opened 2022-06-01 05:14 UTC
PU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: runs/cgh-rave-cambini-24k/prior
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [1]

  | Name             | Type                  | Params
-----------------------------------------------------------
0 | diagonal_shift   | DiagonalShift         | 0     
1 | quantized_normal | QuantizedNormal       | 0     
2 | synth            | RecursiveScriptModule | 64.2 M
3 | pre_net          | Sequential            | 49.7 K
4 | residuals        | ModuleList            | 19.7 M
5 | post_net         | Sequential            | 78.1 K
-----------------------------------------------------------
84.0 M    Trainable params
0         Non-trainable params
84.0 M    Total params
335.864   Total estimated model params size (MB)
Sanity Checking DataLoader 0:   0%|                                                                                                              | 0/1 [00:00<?, ?it/s]
/evafs/speech/RAVE/prior/core.py:52: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
  i = i // self.groups
Traceback (most recent call last):
  File "/evafs/speech/RAVE/train_prior.py", line 128, in <module>
    trainer.fit(model, train, val, ckpt_path=run)
  File "/opt/conda/envs/RVAE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "/opt/conda/envs/RVAE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 721, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/opt/conda/envs/RVAE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/opt/conda/envs/RVAE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/opt/conda/envs/RVAE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/opt/conda/envs/RVAE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_train
    self._run_sanity_check()
  File "/opt/conda/envs/RVAE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1411, in _run_sanity_check
    val_loop.run()
  File "/opt/conda/envs/RVAE/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/envs/RVAE/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 153, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/opt/conda/envs/RVAE/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/envs/RVAE/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 127, in advance
    output = self._evaluation_step(**kwargs)
  File "/opt/conda/envs/RVAE/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 222, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/opt/conda/envs/RVAE/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1763, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/opt/conda/envs/RVAE/lib/python3.9/site-packages/pytorch_lightning/strategies/strategy.py", line 344, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/evafs/speech/RAVE/prior/model.py", line 147, in validation_step
    x = torch.argmax(self.split_classes(x[..., 1:]), -1)
  File "/evafs/speech/RAVE/prior/model.py", line 107, in split_classes
    x = x.reshape(x.shape[0], x.shape[1], self.data_size, -1)
RuntimeError: cannot reshape tensor of 0 elements into shape [4, 0, 128, -1] because the unspecified dimension size -1 can be any value and is ambiguous

any reply will be appreciated,
thanks in advance!

**Comment by caillonantoine** [comment] 2022-06-01 09:46
Please format your issue correctly when you are quoting code ! Duplicate of #45 , basically you shoud either increase your dataset size or **not** crop your latent size to 128

**Closed by caillonantoine** 2022-06-01 09:46 UTC

**Comment by meadow163** [comment] 2022-06-01 09:52
> Please format your issue correctly when you are quoting code ! Duplicate of #45 , basically you shoud either increase your dataset size or **not** crop your latent size to 128

sorry about the format. thanks for your reply really!

**Comment by caillonantoine** [comment] 2022-06-01 09:55
No problem :)

**Comment by smithee77** [comment] 2022-08-08 22:20
Hi @meadow163 @caillonantoine in Colab code...how can change the latent size cropping? I'm having same issue and I'm increasing dataset, but still getting error

many thanks
